/**
 * Workspace-Aware Mock Data
 * 
 * This file contains mock data for development purposes.
 * 
 * ⚠️ WARNING: This file should NOT be imported in production builds.
 * Mock data is for development/testing only.
 * 
 * To disable mock data:
 * - Remove imports of this file
 * - Ensure Redux slices initialize with empty arrays
 */

import { Event } from '@/src/types/event';
import { MedicalItem } from '@/src/types/inventory';
import { ScheduleItem } from '@/src/types/schedule';

// Helper to generate date offset from today
const getDateOffset = (daysAgo: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString().split('T')[0];
};

// Helper to generate date offset with time
const getDateTimeOffset = (daysAgo: number, hours: number = 9): string => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  date.setHours(hours, 0, 0, 0);
  return date.toISOString();
};

// ============================================================================
// Personal Workspace Mock Data
// ============================================================================

export const personalTransactions = [
  {
    date: getDateOffset(0),
    amount: 5200,
    type: 'income' as const,
    category: 'Salary',
    account: 'card' as const,
    notes: 'Monthly salary deposit',
    tags: ['monthly', 'work', 'paycheck'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(1),
    amount: 85.50,
    type: 'expense' as const,
    category: 'Food & Dining',
    account: 'card' as const,
    notes: 'Weekend dinner at restaurant',
    tags: ['food', 'dining'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(2),
    amount: 45,
    type: 'expense' as const,
    category: 'Transportation',
    account: 'cash' as const,
    notes: 'Gas for car',
    tags: ['car', 'fuel'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(3),
    amount: 1200,
    type: 'income' as const,
    category: 'Freelance',
    account: 'card' as const,
    notes: 'Side project payment',
    tags: ['freelance', 'side-hustle'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(4),
    amount: 35,
    type: 'expense' as const,
    category: 'Shopping',
    account: 'card' as const,
    notes: 'New headphones',
    tags: ['electronics'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(5),
    amount: 180,
    type: 'expense' as const,
    category: 'Bills & Utilities',
    account: 'card' as const,
    notes: 'Internet bill',
    tags: ['bills', 'utilities'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(6),
    amount: 250,
    type: 'expense' as const,
    category: 'Healthcare',
    account: 'card' as const,
    notes: 'Doctor visit copay',
    tags: ['health', 'medical'],
    createdBy: 'User',
    deleted: false,
  },
  {
    date: getDateOffset(7),
    amount: 65,
    type: 'expense' as const,
    category: 'Entertainment',
    account: 'card' as const,
    notes: 'Concert tickets',
    tags: ['entertainment', 'music'],
    createdBy: 'User',
    deleted: false,
  },
];

export const personalInventory: MedicalItem[] = [
  {
    id: 'p-med-1',
    name: 'Vitamin D3 2000IU',
    type: 'medicine' as const,
    category: 'Vitamins',
    quantity: 60,
    unit: 'tablets' as const,
    expiryDate: '2025-12-15',
    lowStockThreshold: 15,
    status: 'active' as const,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-med-2',
    name: 'Melatonin 5mg',
    type: 'medicine' as const,
    category: 'Sleep Aid',
    quantity: 30,
    unit: 'tablets' as const,
    expiryDate: '2025-09-20',
    lowStockThreshold: 10,
    status: 'active' as const,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-med-3',
    name: 'Ibuprofen 400mg',
    type: 'medicine' as const,
    category: 'Pain Relief',
    quantity: 8,
    unit: 'bottles' as const,
    expiryDate: '2025-08-10',
    lowStockThreshold: 3,
    status: 'active' as const,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-med-4',
    name: 'Creatine Monohydrate',
    type: 'medicine' as const,
    category: 'Supplements',
    quantity: 2,
    unit: 'bottles' as const,
    expiryDate: '2025-11-30',
    lowStockThreshold: 1,
    status: 'active' as const,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-med-5',
    name: 'Zinc 50mg',
    type: 'medicine' as const,
    category: 'Immunity',
    quantity: 45,
    unit: 'tablets' as const,
    expiryDate: '2025-07-05',
    lowStockThreshold: 15,
    status: 'active' as const,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-med-6',
    name: 'Fish Oil 1000mg',
    type: 'medicine' as const,
    category: 'Supplements',
    quantity: 0,
    unit: 'bottles' as const,
    expiryDate: '2025-10-20',
    lowStockThreshold: 1,
    status: 'out_of_stock' as const,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
];

export const personalSchedule: ScheduleItem[] = [
  {
    id: 'p-sch-1',
    medicineName: 'Vitamin D3 2000IU',
    personId: 'self',
    personName: 'Myself',
    dosageAmount: '1',
    dosageUnit: 'tablet' as const,
    times: ['08:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(30),
    isActive: true,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-sch-2',
    medicineName: 'Melatonin 5mg',
    personId: 'self',
    personName: 'Myself',
    dosageAmount: '1',
    dosageUnit: 'tablet' as const,
    times: ['22:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(30),
    isActive: true,
    notes: 'Take 30 mins before bed',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-sch-3',
    medicineName: 'Fish Oil 1000mg',
    personId: 'self',
    personName: 'Myself',
    dosageAmount: '2',
    dosageUnit: 'capsule' as const,
    times: ['08:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(30),
    isActive: true,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
];

export const personalEvents: Event[] = [
  {
    id: 'p-evt-1',
    title: 'Morning Workout',
    description: 'Gym session - strength training',
    startDateTime: getDateTimeOffset(0, 6),
    endDateTime: getDateTimeOffset(0, 7),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'daily',
    createdBy: 'Myself',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-evt-2',
    title: 'Weekly Review',
    description: 'Review weekly goals and progress',
    startDateTime: getDateTimeOffset(1, 18),
    endDateTime: getDateTimeOffset(1, 19),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'weekly',
    createdBy: 'Myself',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-evt-3',
    title: 'Dentist Appointment',
    description: 'Routine checkup',
    startDateTime: getDateTimeOffset(3, 10),
    endDateTime: getDateTimeOffset(3, 11),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'none',
    createdBy: 'Myself',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: 'p-evt-4',
    title: 'Friend\'s Birthday Dinner',
    description: 'Celebrating at Italian restaurant',
    startDateTime: getDateTimeOffset(5, 19),
    endDateTime: getDateTimeOffset(5, 22),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'none',
    createdBy: 'Myself',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
];

// ============================================================================
// Family Workspace Mock Data
// ============================================================================

export const familyTransactions = [
  {
    date: getDateOffset(0),
    amount: 6500,
    type: 'income' as const,
    category: 'Salary',
    account: 'card' as const,
    notes: 'Combined household income',
    tags: ['household', 'income'],
    createdBy: 'Parent 1',
    deleted: false,
  },
  {
    date: getDateOffset(0),
    amount: 3200,
    type: 'income' as const,
    category: 'Salary',
    account: 'card' as const,
    notes: 'Secondary income',
    tags: ['household', 'income'],
    createdBy: 'Parent 2',
    deleted: false,
  },
  {
    date: getDateOffset(1),
    amount: 156.80,
    type: 'expense' as const,
    category: 'Food & Dining',
    account: 'card' as const,
    notes: 'Weekly grocery shopping',
    tags: ['groceries', 'household'],
    createdBy: 'Parent 1',
    deleted: false,
  },
  {
    date: getDateOffset(2),
    amount: 2500,
    type: 'expense' as const,
    category: 'Housing',
    account: 'card' as const,
    notes: 'Monthly mortgage payment',
    tags: ['housing', 'mortgage'],
    createdBy: 'Parent 1',
    deleted: false,
  },
  {
    date: getDateOffset(3),
    amount: 89.99,
    type: 'expense' as const,
    category: 'Utilities',
    account: 'card' as const,
    notes: 'Electric and water bill',
    tags: ['utilities', 'bills'],
    createdBy: 'Parent 1',
    deleted: false,
  },
  {
    date: getDateOffset(4),
    amount: 450,
    type: 'expense' as const,
    category: 'Education',
    account: 'card' as const,
    notes: 'School supplies and fees',
    tags: ['kids', 'school'],
    createdBy: 'Parent 2',
    deleted: false,
  },
  {
    date: getDateOffset(5),
    amount: 120,
    type: 'expense' as const,
    category: 'Transportation',
    account: 'cash' as const,
    notes: 'Car maintenance',
    tags: ['car', 'maintenance'],
    createdBy: 'Parent 1',
    deleted: false,
  },
  {
    date: getDateOffset(6),
    amount: 75,
    type: 'expense' as const,
    category: 'Healthcare',
    account: 'card' as const,
    notes: 'Prescription refill',
    tags: ['health', 'medical'],
    createdBy: 'Parent 2',
    deleted: false,
  },
  {
    date: getDateOffset(7),
    amount: 199,
    type: 'expense' as const,
    category: 'Insurance',
    account: 'card' as const,
    notes: 'Car insurance premium',
    tags: ['insurance', 'car'],
    createdBy: 'Parent 1',
    deleted: false,
  },
  {
    date: getDateOffset(8),
    amount: 55,
    type: 'expense' as const,
    category: 'Entertainment',
    account: 'card' as const,
    notes: 'Family movie night',
    tags: ['family', 'entertainment'],
    createdBy: 'Parent 2',
    deleted: false,
  },
];

export const familyInventory: MedicalItem[] = [
  {
    id: 'f-med-1',
    name: 'Amoxicillin 250mg',
    type: 'medicine' as const,
    category: 'Antibiotics',
    quantity: 12,
    unit: 'bottles' as const,
    expiryDate: '2025-06-30',
    lowStockThreshold: 3,
    status: 'active' as const,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-2',
    name: 'Cetirizine 10mg',
    type: 'medicine' as const,
    category: 'Allergy',
    quantity: 3,
    unit: 'strips' as const,
    tabletsPerStrip: 10,
    expiryDate: '2025-08-15',
    lowStockThreshold: 2,
    status: 'active' as const,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-3',
    name: 'Paracetamol 500mg',
    type: 'medicine' as const,
    category: 'Pain Relief',
    quantity: 100,
    unit: 'tablets' as const,
    expiryDate: '2025-12-01',
    lowStockThreshold: 30,
    status: 'active' as const,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-4',
    name: 'Omeprazole 20mg',
    type: 'medicine' as const,
    category: 'Gastric',
    quantity: 15,
    unit: 'tablets' as const,
    expiryDate: '2025-09-20',
    lowStockThreshold: 10,
    status: 'active' as const,
    assignedTo: 'Parent 1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-5',
    name: 'Metformin 500mg',
    type: 'medicine' as const,
    category: 'Diabetes',
    quantity: 60,
    unit: 'tablets' as const,
    expiryDate: '2025-11-10',
    lowStockThreshold: 20,
    status: 'active' as const,
    assignedTo: 'Parent 2',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-6',
    name: 'Salbutamol Inhaler',
    type: 'medicine' as const,
    category: 'Respiratory',
    quantity: 1,
    unit: 'bottles' as const,
    expiryDate: '2025-07-30',
    lowStockThreshold: 1,
    status: 'active' as const,
    assignedTo: 'Child 1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-7',
    name: 'Multivitamin Kids',
    type: 'medicine' as const,
    category: 'Vitamins',
    quantity: 2,
    unit: 'bottles' as const,
    expiryDate: '2025-10-05',
    lowStockThreshold: 1,
    status: 'active' as const,
    assignedTo: 'Child 1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-med-8',
    name: 'Calcium + Vitamin D',
    type: 'medicine' as const,
    category: 'Vitamins',
    quantity: 4,
    unit: 'bottles' as const,
    expiryDate: '2025-08-25',
    lowStockThreshold: 2,
    status: 'active' as const,
    assignedTo: 'Parent 2',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const familySchedule: ScheduleItem[] = [
  {
    id: 'f-sch-1',
    medicineName: 'Metformin 500mg',
    personId: 'parent2',
    personName: 'Parent 2',
    dosageAmount: '1',
    dosageUnit: 'tablet' as const,
    times: ['08:00', '20:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(60),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-sch-2',
    medicineName: 'Omeprazole 20mg',
    personId: 'parent1',
    personName: 'Parent 1',
    dosageAmount: '1',
    dosageUnit: 'tablet' as const,
    times: ['07:30'],
    frequency: 'daily' as const,
    startDate: getDateOffset(60),
    isActive: true,
    notes: 'Take before breakfast',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-sch-3',
    medicineName: 'Salbutamol Inhaler',
    personId: 'child1',
    personName: 'Child 1',
    dosageAmount: '2',
    dosageUnit: 'injection' as const,
    times: ['07:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(60),
    isActive: true,
    notes: 'As needed for asthma symptoms',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-sch-4',
    medicineName: 'Multivitamin Kids',
    personId: 'child1',
    personName: 'Child 1',
    dosageAmount: '1',
    dosageUnit: 'tablet' as const,
    times: ['08:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(60),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-sch-5',
    medicineName: 'Cetirizine 10mg',
    personId: 'child2',
    personName: 'Child 2',
    dosageAmount: '0.5',
    dosageUnit: 'tablet' as const,
    times: ['09:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(30),
    isActive: true,
    notes: 'For seasonal allergies',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-sch-6',
    medicineName: 'Calcium + Vitamin D',
    personId: 'parent2',
    personName: 'Parent 2',
    dosageAmount: '2',
    dosageUnit: 'tablet' as const,
    times: ['08:00', '20:00'],
    frequency: 'daily' as const,
    startDate: getDateOffset(60),
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

export const familyEvents: Event[] = [
  {
    id: 'f-evt-1',
    title: 'School Run',
    description: 'Drop kids at school',
    startDateTime: getDateTimeOffset(0, 7),
    endDateTime: getDateTimeOffset(0, 8),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'daily',
    createdBy: 'Parent 1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-evt-2',
    title: 'Family Dinner',
    description: 'Weekly family dinner together',
    startDateTime: getDateTimeOffset(2, 18),
    endDateTime: getDateTimeOffset(2, 20),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'weekly',
    createdBy: 'Parent 1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-evt-3',
    title: 'Doctor Checkup - Child 1',
    description: 'Annual physical examination',
    startDateTime: getDateTimeOffset(5, 9),
    endDateTime: getDateTimeOffset(5, 10),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'none',
    createdBy: 'Parent 2',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-evt-4',
    title: 'Parent-Teacher Conference',
    description: 'Meeting with teachers',
    startDateTime: getDateTimeOffset(10, 15),
    endDateTime: getDateTimeOffset(10, 17),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'none',
    createdBy: 'Parent 1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'f-evt-5',
    title: 'Family Game Night',
    description: 'Board games and snacks',
    startDateTime: getDateTimeOffset(6, 19),
    endDateTime: getDateTimeOffset(6, 22),
    isAllDay: false,
    isMultiDay: false,
    recurrence: 'weekly',
    createdBy: 'Parent 2',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
];

// ============================================================================
// Main Mock Data Export
// ============================================================================

export interface WorkspaceMockData {
  transactions: typeof personalTransactions;
  inventory: typeof personalInventory;
  schedule: typeof personalSchedule;
  events: typeof personalEvents;
}

export const mockData: Record<string, WorkspaceMockData> = {
  Personal: {
    transactions: personalTransactions,
    inventory: personalInventory,
    schedule: personalSchedule,
    events: personalEvents,
  },
  Family: {
    transactions: familyTransactions,
    inventory: familyInventory,
    schedule: familySchedule,
    events: familyEvents,
  },
};

// Helper to get mock data for a workspace
export const getMockDataForWorkspace = (workspaceId: string): WorkspaceMockData => {
  const data = mockData[workspaceId];
  if (!data) {
    console.warn(`No mock data found for workspace: ${workspaceId}. Using Personal as fallback.`);
    return mockData['Personal'];
  }
  return data;
};

// Helper to check if workspace has mock data
export const hasMockData = (workspaceId: string): boolean => {
  return workspaceId in mockData;
};

